# permissions for end users to edit adapters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: adapter-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: adapter-operator
    app.kubernetes.io/part-of: adapter-operator
    app.kubernetes.io/managed-by: kustomize
  name: adapter-editor-role
rules:
- apiGroups:
  - api.my.domain
  resources:
  - adapters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.my.domain
  resources:
  - adapters/status
  verbs:
  - get
